include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
  errors:
    invalid_annotation_target: ignore
    use_build_context_synchronously: ignore
