name: zup_app
publish_to: none

environment:
  sdk: ^3.5.2
  flutter: 3.27.3

dependencies:
  build_runner: ^2.4.12
  flutter:
    sdk: flutter
  flutter_gen_runner: ^5.7.0
  flutter_svg: ^2.0.10+1
  routefly:
    git:
      url: https://github.com/RyanHolanda/routefly.git # TODO: Pull request sent to the original repo, wait for merge and then update the dependency for the original.
      ref: hotfix-vercel
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.7.0
  web3kit:
    # path: ../web3kit
    git:
      url: https://github.com/Zup-Protocol/web3kit.git
      ref: main
  zup_ui_kit:
    # path: ../zup_ui_kit
    git:
      url: https://github.com/Zup-Protocol/zup-ui-kit.git
      ref: main
  zup_core:
    # path: ../zup_core
    git:
      url: https://github.com/Zup-Protocol/zup-core.git
      ref: main
  freezed_annotation: ^2.4.4
  flutter_bloc: ^8.1.6
  collection: ^1.18.0
  json_annotation: ^4.9.0
  url_launcher: ^6.3.0
  cached_network_image: ^3.4.1
  skeletonizer: ^1.4.2
  shared_preferences: ^2.3.2
  dio: ^5.7.0
  fake_async: ^1.3.1
  intl: ^0.19.0
  flutter_inset_box_shadow: ^1.0.8
  lottie: ^3.1.2
  equatable: ^2.0.5
  decimal: ^3.0.2
  flutter_animate: ^4.5.0
  clock: ^1.1.1
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  golden_toolkit: ^0.15.0
  mocktail_image_network: ^1.2.0
  mocktail: ^1.0.4
  json_serializable: ^6.8.0
  url_launcher_platform_interface: ^2.3.2
  plugin_platform_interface: ^2.1.8

flutter_gen:
  output: lib/gen/
  line_length: 200
  integrations:
    flutter_svg: true
    lottie: true
  assets:
    enabled: true
  colors:
    enabled: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/logos/
    - assets/lotties/
  fonts:
    - family: "SNPro"
      fonts:
        - asset: assets/fonts/SNPro-Heavy.otf
          weight: 900
        - asset: assets/fonts/SNPro-Black.otf
          weight: 800
        - asset: assets/fonts/SNPro-Bold.otf
          weight: 700
        - asset: assets/fonts/SNPro-Semibold.otf
          weight: 600
        - asset: assets/fonts/SNPro-Medium.otf
          weight: 500
        - asset: assets/fonts/SNPro-Regular.otf
          weight: 400
        - asset: assets/fonts/SNPro-Light.otf
          weight: 300
        - asset: assets/fonts/SNPro-Thin.otf
          weight: 200
        - asset: assets/fonts/SNPro-Thin.otf
          weight: 100
