// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/app_layout.dart' as a1;
import 'app/create/create_page.dart' as a2;
import 'app/positions/positions_page.dart' as a0;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/positions',
        parent: '/',
        uri: Uri.parse('/positions'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a0.PositionsPage(),
        ),
      ),
      RouteEntity(
        key: '/',
        uri: Uri.parse('/'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.AppPage(),
        ),
      ),
      RouteEntity(
        key: '/create',
        parent: '/',
        uri: Uri.parse('/create'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a2.CreatePage(),
        ),
      ),
    ];

const routePaths = (
  path: '/',
  positions: '/positions',
  create: '/create',
);
