// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/add/add_page.dart' as a0;
import 'app/app_layout.dart' as a2;
import 'app/positions/positions_page.dart' as a1;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/add',
        parent: '/',
        uri: Uri.parse('/add'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a0.AddPage(),
        ),
      ),
      RouteEntity(
        key: '/positions',
        parent: '/',
        uri: Uri.parse('/positions'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.PositionsPage(),
        ),
      ),
      RouteEntity(
        key: '/',
        uri: Uri.parse('/'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a2.AppPage(),
        ),
      ),
    ];

const routePaths = (
  path: '/',
  add: '/add',
  positions: '/positions',
);
