// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'zup_app.dart';

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/positions',
        parent: '/',
        uri: Uri.parse('/positions'),
        routeBuilder: b0Builder,
      ),
      RouteEntity(
        key: '/',
        uri: Uri.parse('/'),
        routeBuilder: b1Builder,
      ),
      RouteEntity(
        key: '/create/deposit',
        parent: '/',
        uri: Uri.parse('/create/deposit'),
        routeBuilder: b2Builder,
      ),
      RouteEntity(
        key: '/create',
        parent: '/',
        uri: Uri.parse('/create'),
        routeBuilder: b3Builder,
      ),
    ];

const routePaths = (
  path: '/',
  positions: '/positions',
  create: (
    path: '/create',
    deposit: '/create/deposit',
  ),
);
