// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:flutter/widgets.dart';
import 'package:routefly/routefly.dart';

import 'app/app_layout.dart' as a1;
import 'app/create/create_page.dart' as a3;
import 'app/create/deposit/deposit_page.dart' as a2;
import 'app/positions/positions_page.dart' as a0;

Route b0Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a0.PositionsPage(),
    );
Route b1Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a1.AppPage(),
    );
Route b2Builder(BuildContext context, RouteSettings settings) =>
    a2.routeBuilder(context, settings);
Route b3Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a3.CreatePage(),
    );
