name: "Pull Request"

on:
  pull_request:
    branches:
      - main
    paths:
      - "lib/**"
      - "test/**"
      - "assets/**"
jobs:
  run-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: SpicyPizza/create-envfile@v2.0.3
        with:
          fail_on_empty: false
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.5.2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.27.3
      - name: Install dependencies
        run: make install
      - name: Run tests
        run: flutter test --test-randomize-ordering-seed=random
